version: "3"
services:
  database:
    image: "numian/postgres-sfcgal:latest"
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
volumes:
  database-data: